/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViolationsRouteImport } from './routes/violations'
import { Route as ToolkitRouteImport } from './routes/toolkit'
import { Route as ThreatIndexRouteImport } from './routes/threat-index'
import { Route as TailSearchRouteImport } from './routes/tail-search'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PodcastsRouteImport } from './routes/podcasts'
import { Route as OperatorsRouteImport } from './routes/operators'
import { Route as MosaicRouteImport } from './routes/mosaic'
import { Route as MlDetectionsRouteImport } from './routes/ml-detections'
import { Route as MilitaryRouteImport } from './routes/military'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as HowToReadRouteImport } from './routes/how-to-read'
import { Route as ForeignRouteImport } from './routes/foreign'
import { Route as FindingsRouteImport } from './routes/findings'
import { Route as CoordinationRouteImport } from './routes/coordination'
import { Route as CitationsRouteImport } from './routes/citations'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as ActRouteImport } from './routes/act'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolkitIndexRouteImport } from './routes/toolkit.index'
import { Route as ToolkitFoiaRouteImport } from './routes/toolkit.foia'
import { Route as ApiPublicTtsRouteImport } from './routes/api/public/tts'

const ViolationsRoute = ViolationsRouteImport.update({
  id: '/violations',
  path: '/violations',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolkitRoute = ToolkitRouteImport.update({
  id: '/toolkit',
  path: '/toolkit',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatIndexRoute = ThreatIndexRouteImport.update({
  id: '/threat-index',
  path: '/threat-index',
  getParentRoute: () => rootRouteImport,
} as any)
const TailSearchRoute = TailSearchRouteImport.update({
  id: '/tail-search',
  path: '/tail-search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastsRoute = PodcastsRouteImport.update({
  id: '/podcasts',
  path: '/podcasts',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorsRoute = OperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => rootRouteImport,
} as any)
const MosaicRoute = MosaicRouteImport.update({
  id: '/mosaic',
  path: '/mosaic',
  getParentRoute: () => rootRouteImport,
} as any)
const MlDetectionsRoute = MlDetectionsRouteImport.update({
  id: '/ml-detections',
  path: '/ml-detections',
  getParentRoute: () => rootRouteImport,
} as any)
const MilitaryRoute = MilitaryRouteImport.update({
  id: '/military',
  path: '/military',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToReadRoute = HowToReadRouteImport.update({
  id: '/how-to-read',
  path: '/how-to-read',
  getParentRoute: () => rootRouteImport,
} as any)
const ForeignRoute = ForeignRouteImport.update({
  id: '/foreign',
  path: '/foreign',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsRoute = FindingsRouteImport.update({
  id: '/findings',
  path: '/findings',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinationRoute = CoordinationRouteImport.update({
  id: '/coordination',
  path: '/coordination',
  getParentRoute: () => rootRouteImport,
} as any)
const CitationsRoute = CitationsRouteImport.update({
  id: '/citations',
  path: '/citations',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ActRoute = ActRouteImport.update({
  id: '/act',
  path: '/act',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolkitIndexRoute = ToolkitIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolkitRoute,
} as any)
const ToolkitFoiaRoute = ToolkitFoiaRouteImport.update({
  id: '/foia',
  path: '/foia',
  getParentRoute: () => ToolkitRoute,
} as any)
const ApiPublicTtsRoute = ApiPublicTtsRouteImport.update({
  id: '/api/public/tts',
  path: '/api/public/tts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/act': typeof ActRoute
  '/cases': typeof CasesRoute
  '/citations': typeof CitationsRoute
  '/coordination': typeof CoordinationRoute
  '/findings': typeof FindingsRoute
  '/foreign': typeof ForeignRoute
  '/how-to-read': typeof HowToReadRoute
  '/legal': typeof LegalRoute
  '/live': typeof LiveRoute
  '/methodology': typeof MethodologyRoute
  '/military': typeof MilitaryRoute
  '/ml-detections': typeof MlDetectionsRoute
  '/mosaic': typeof MosaicRoute
  '/operators': typeof OperatorsRoute
  '/podcasts': typeof PodcastsRoute
  '/reports': typeof ReportsRoute
  '/rules': typeof RulesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tail-search': typeof TailSearchRoute
  '/threat-index': typeof ThreatIndexRoute
  '/toolkit': typeof ToolkitRouteWithChildren
  '/violations': typeof ViolationsRoute
  '/toolkit/foia': typeof ToolkitFoiaRoute
  '/toolkit/': typeof ToolkitIndexRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/act': typeof ActRoute
  '/cases': typeof CasesRoute
  '/citations': typeof CitationsRoute
  '/coordination': typeof CoordinationRoute
  '/findings': typeof FindingsRoute
  '/foreign': typeof ForeignRoute
  '/how-to-read': typeof HowToReadRoute
  '/legal': typeof LegalRoute
  '/live': typeof LiveRoute
  '/methodology': typeof MethodologyRoute
  '/military': typeof MilitaryRoute
  '/ml-detections': typeof MlDetectionsRoute
  '/mosaic': typeof MosaicRoute
  '/operators': typeof OperatorsRoute
  '/podcasts': typeof PodcastsRoute
  '/reports': typeof ReportsRoute
  '/rules': typeof RulesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tail-search': typeof TailSearchRoute
  '/threat-index': typeof ThreatIndexRoute
  '/violations': typeof ViolationsRoute
  '/toolkit/foia': typeof ToolkitFoiaRoute
  '/toolkit': typeof ToolkitIndexRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/act': typeof ActRoute
  '/cases': typeof CasesRoute
  '/citations': typeof CitationsRoute
  '/coordination': typeof CoordinationRoute
  '/findings': typeof FindingsRoute
  '/foreign': typeof ForeignRoute
  '/how-to-read': typeof HowToReadRoute
  '/legal': typeof LegalRoute
  '/live': typeof LiveRoute
  '/methodology': typeof MethodologyRoute
  '/military': typeof MilitaryRoute
  '/ml-detections': typeof MlDetectionsRoute
  '/mosaic': typeof MosaicRoute
  '/operators': typeof OperatorsRoute
  '/podcasts': typeof PodcastsRoute
  '/reports': typeof ReportsRoute
  '/rules': typeof RulesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tail-search': typeof TailSearchRoute
  '/threat-index': typeof ThreatIndexRoute
  '/toolkit': typeof ToolkitRouteWithChildren
  '/violations': typeof ViolationsRoute
  '/toolkit/foia': typeof ToolkitFoiaRoute
  '/toolkit/': typeof ToolkitIndexRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/act'
    | '/cases'
    | '/citations'
    | '/coordination'
    | '/findings'
    | '/foreign'
    | '/how-to-read'
    | '/legal'
    | '/live'
    | '/methodology'
    | '/military'
    | '/ml-detections'
    | '/mosaic'
    | '/operators'
    | '/podcasts'
    | '/reports'
    | '/rules'
    | '/sitemap.xml'
    | '/tail-search'
    | '/threat-index'
    | '/toolkit'
    | '/violations'
    | '/toolkit/foia'
    | '/toolkit/'
    | '/api/public/tts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/act'
    | '/cases'
    | '/citations'
    | '/coordination'
    | '/findings'
    | '/foreign'
    | '/how-to-read'
    | '/legal'
    | '/live'
    | '/methodology'
    | '/military'
    | '/ml-detections'
    | '/mosaic'
    | '/operators'
    | '/podcasts'
    | '/reports'
    | '/rules'
    | '/sitemap.xml'
    | '/tail-search'
    | '/threat-index'
    | '/violations'
    | '/toolkit/foia'
    | '/toolkit'
    | '/api/public/tts'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/act'
    | '/cases'
    | '/citations'
    | '/coordination'
    | '/findings'
    | '/foreign'
    | '/how-to-read'
    | '/legal'
    | '/live'
    | '/methodology'
    | '/military'
    | '/ml-detections'
    | '/mosaic'
    | '/operators'
    | '/podcasts'
    | '/reports'
    | '/rules'
    | '/sitemap.xml'
    | '/tail-search'
    | '/threat-index'
    | '/toolkit'
    | '/violations'
    | '/toolkit/foia'
    | '/toolkit/'
    | '/api/public/tts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActRoute: typeof ActRoute
  CasesRoute: typeof CasesRoute
  CitationsRoute: typeof CitationsRoute
  CoordinationRoute: typeof CoordinationRoute
  FindingsRoute: typeof FindingsRoute
  ForeignRoute: typeof ForeignRoute
  HowToReadRoute: typeof HowToReadRoute
  LegalRoute: typeof LegalRoute
  LiveRoute: typeof LiveRoute
  MethodologyRoute: typeof MethodologyRoute
  MilitaryRoute: typeof MilitaryRoute
  MlDetectionsRoute: typeof MlDetectionsRoute
  MosaicRoute: typeof MosaicRoute
  OperatorsRoute: typeof OperatorsRoute
  PodcastsRoute: typeof PodcastsRoute
  ReportsRoute: typeof ReportsRoute
  RulesRoute: typeof RulesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TailSearchRoute: typeof TailSearchRoute
  ThreatIndexRoute: typeof ThreatIndexRoute
  ToolkitRoute: typeof ToolkitRouteWithChildren
  ViolationsRoute: typeof ViolationsRoute
  ApiPublicTtsRoute: typeof ApiPublicTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/violations': {
      id: '/violations'
      path: '/violations'
      fullPath: '/violations'
      preLoaderRoute: typeof ViolationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolkit': {
      id: '/toolkit'
      path: '/toolkit'
      fullPath: '/toolkit'
      preLoaderRoute: typeof ToolkitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-index': {
      id: '/threat-index'
      path: '/threat-index'
      fullPath: '/threat-index'
      preLoaderRoute: typeof ThreatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tail-search': {
      id: '/tail-search'
      path: '/tail-search'
      fullPath: '/tail-search'
      preLoaderRoute: typeof TailSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcasts': {
      id: '/podcasts'
      path: '/podcasts'
      fullPath: '/podcasts'
      preLoaderRoute: typeof PodcastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operators': {
      id: '/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof OperatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mosaic': {
      id: '/mosaic'
      path: '/mosaic'
      fullPath: '/mosaic'
      preLoaderRoute: typeof MosaicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ml-detections': {
      id: '/ml-detections'
      path: '/ml-detections'
      fullPath: '/ml-detections'
      preLoaderRoute: typeof MlDetectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/military': {
      id: '/military'
      path: '/military'
      fullPath: '/military'
      preLoaderRoute: typeof MilitaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-read': {
      id: '/how-to-read'
      path: '/how-to-read'
      fullPath: '/how-to-read'
      preLoaderRoute: typeof HowToReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foreign': {
      id: '/foreign'
      path: '/foreign'
      fullPath: '/foreign'
      preLoaderRoute: typeof ForeignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings': {
      id: '/findings'
      path: '/findings'
      fullPath: '/findings'
      preLoaderRoute: typeof FindingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordination': {
      id: '/coordination'
      path: '/coordination'
      fullPath: '/coordination'
      preLoaderRoute: typeof CoordinationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citations': {
      id: '/citations'
      path: '/citations'
      fullPath: '/citations'
      preLoaderRoute: typeof CitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/act': {
      id: '/act'
      path: '/act'
      fullPath: '/act'
      preLoaderRoute: typeof ActRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolkit/': {
      id: '/toolkit/'
      path: '/'
      fullPath: '/toolkit/'
      preLoaderRoute: typeof ToolkitIndexRouteImport
      parentRoute: typeof ToolkitRoute
    }
    '/toolkit/foia': {
      id: '/toolkit/foia'
      path: '/foia'
      fullPath: '/toolkit/foia'
      preLoaderRoute: typeof ToolkitFoiaRouteImport
      parentRoute: typeof ToolkitRoute
    }
    '/api/public/tts': {
      id: '/api/public/tts'
      path: '/api/public/tts'
      fullPath: '/api/public/tts'
      preLoaderRoute: typeof ApiPublicTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ToolkitRouteChildren {
  ToolkitFoiaRoute: typeof ToolkitFoiaRoute
  ToolkitIndexRoute: typeof ToolkitIndexRoute
}

const ToolkitRouteChildren: ToolkitRouteChildren = {
  ToolkitFoiaRoute: ToolkitFoiaRoute,
  ToolkitIndexRoute: ToolkitIndexRoute,
}

const ToolkitRouteWithChildren =
  ToolkitRoute._addFileChildren(ToolkitRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActRoute: ActRoute,
  CasesRoute: CasesRoute,
  CitationsRoute: CitationsRoute,
  CoordinationRoute: CoordinationRoute,
  FindingsRoute: FindingsRoute,
  ForeignRoute: ForeignRoute,
  HowToReadRoute: HowToReadRoute,
  LegalRoute: LegalRoute,
  LiveRoute: LiveRoute,
  MethodologyRoute: MethodologyRoute,
  MilitaryRoute: MilitaryRoute,
  MlDetectionsRoute: MlDetectionsRoute,
  MosaicRoute: MosaicRoute,
  OperatorsRoute: OperatorsRoute,
  PodcastsRoute: PodcastsRoute,
  ReportsRoute: ReportsRoute,
  RulesRoute: RulesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TailSearchRoute: TailSearchRoute,
  ThreatIndexRoute: ThreatIndexRoute,
  ToolkitRoute: ToolkitRouteWithChildren,
  ViolationsRoute: ViolationsRoute,
  ApiPublicTtsRoute: ApiPublicTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
